# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_number', models.IntegerField(primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=255, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('file_date', models.DateTimeField(verbose_name='fecha admision')),
                ('record_time_stamp', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_number', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_initial', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, max_length=255)),
                ('address_line_1', models.CharField(blank=True, max_length=600)),
                ('address_line_2', models.CharField(blank=True, max_length=600)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('zip_code', models.IntegerField(blank=True)),
                ('zip_plu4', models.IntegerField(blank=True)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('bad_addr_flag', models.CharField(blank=True, max_length=255)),
                ('home_phone', models.CharField(blank=True, max_length=255)),
                ('work_phone', models.CharField(blank=True, max_length=255)),
                ('work_extension', models.CharField(blank=True, max_length=255)),
                ('cell_phone', models.CharField(blank=True, max_length=255)),
                ('emer_phone', models.CharField(blank=True, max_length=255)),
                ('ssn', models.CharField(blank=True, max_length=255)),
                ('driver_license', models.CharField(blank=True, max_length=255)),
                ('date_of_birth', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('barcode', models.CharField(blank=True, max_length=255)),
                ('club_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_number_de', to='cuentas.Club')),
            ],
        ),
    ]
