# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formadepago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_under_first_name', models.CharField(max_length=255)),
                ('draft_under_last_name', models.CharField(max_length=255)),
                ('bank_routing_number', models.CharField(blank=True, max_length=255)),
                ('bank_account_number', models.CharField(blank=True, max_length=255)),
                ('bank_account_type', models.CharField(blank=True, max_length=255)),
                ('credit_card_number', models.CharField(max_length=255)),
                ('credit_card_expire', models.CharField(max_length=255)),
                ('credit_card_type', models.CharField(max_length=255)),
                ('member_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_number_de', to='cuentas.Member')),
            ],
        ),
    ]
