# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_pagos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire_date', models.DateTimeField(verbose_name='fecha en que inicia la deuda')),
                ('next_due_amount', models.IntegerField(blank=True)),
                ('payments_remaining', models.IntegerField(blank=True)),
                ('balance_remaining', models.IntegerField(blank=True)),
                ('total_past_due_amt', models.IntegerField(blank=True)),
                ('past_due_30_ene', models.IntegerField(blank=True)),
                ('past_due_31_60', models.IntegerField(blank=True)),
                ('past_due_61_90', models.IntegerField(blank=True)),
                ('past_due_91_and_up', models.IntegerField(blank=True)),
                ('late_fees_balance', models.IntegerField(blank=True)),
                ('oldest_late_fee', models.DateTimeField(verbose_name='fecha de servicio mas antiguo')),
                ('oldest_due_date', models.DateTimeField(verbose_name='fecha de la dueda más antigua')),
                ('oldest_amount_due', models.DateTimeField(verbose_name='')),
                ('last_invoice_scheduled', models.DateTimeField(verbose_name='ultima factura programada')),
                ('pending_cancel_amount', models.IntegerField(blank=True)),
                ('last_late_fee', models.IntegerField(blank=True)),
                ('last_service_fee', models.IntegerField(blank=True)),
                ('member_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_number_deee', to='cuentas.Member')),
            ],
        ),
    ]
