# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=600)),
                ('tlf', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=600)),
                ('email', models.CharField(max_length=600)),
                ('fecha_admision', models.DateTimeField(verbose_name='fecha admision')),
            ],
        ),
    ]
