# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 01:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField(unique=True)),
                ('direccion', models.CharField(max_length=600)),
                ('tlf', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255, unique=True)),
                ('foto', models.ImageField(default='/profiles/no_image.png', upload_to='profiles/')),
                ('fecha_admision', models.DateTimeField(verbose_name='fecha admision')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
