# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_auto_20170730_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(default='/profiles/no_image.png', upload_to=''),
        ),
    ]
